
package com.withgrisha.armsoft.wsdl.tempuri;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TradeService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://5.63.165.246:8888/TradeService/TradeService.svc?wsdl")
public class TradeService
    extends Service
{

    private final static URL TRADESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(TradeService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = TradeService.class.getResource(".");
            url = new URL(baseUrl, "http://5.63.165.246:8888/TradeService/TradeService.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://5.63.165.246:8888/TradeService/TradeService.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TRADESERVICE_WSDL_LOCATION = url;
    }

    public TradeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TradeService() {
        super(TRADESERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "TradeService"));
    }

    /**
     * 
     * @return
     *     returns ITradeService
     */
    @WebEndpoint(name = "BasicHttpBinding_ITradeService")
    public ITradeService getBasicHttpBindingITradeService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ITradeService"), ITradeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITradeService
     */
    @WebEndpoint(name = "BasicHttpBinding_ITradeService")
    public ITradeService getBasicHttpBindingITradeService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ITradeService"), ITradeService.class, features);
    }

}
